# Assignment 2 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [74]:
# required imports
import numpy as np
import fnmatch
import os
import re

Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [75]:
# Here we have intialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set
directory_path = 'files'

In [76]:
#Your code starts here

def read_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        return file.read()


for root, dirs, files in os.walk(directory_path):
    for file_name in files:
        if file_name != 'synonyms.txt':
            file_path = os.path.join(root, file_name)
            # file_content = read_file(file_path)
            files_dict[file_name] = file_count
            file_count+=1
    



#Your code ends here       

Displaying the count of files.

In [77]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [78]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [79]:
#Your code starts here    
def extract_unique_words(file_content):
    # Use regular expression to find words (ignoring punctuation and case)
    words = re.findall(r'\b\w+\b', file_content.lower())
    return set(words)
def get_unique_words(files_dict):
    all_unique_words = set()
    for root, dirs, files in os.walk(directory_path):
        for file_name in files:
            if file_name != 'synonyms.txt':
                file_path = os.path.join(root, file_name)
                file_content = read_file(file_path)
                unique_words = extract_unique_words(file_content)
                all_unique_words.update(unique_words)
    
    return all_unique_words


# Print unique words per file
unique_words = get_unique_words(files_dict)
print('Unique words in every file\n',unique_words)
# Display the count of files
print('count of files',file_count)
#Your code ends here

Unique words in every file
 {'my', 'book', 'is', 'interesting', 'pen', 'this'}
count of files 3


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

- Create Term doc matrix such that colmns will be unique words and all the files will be rows
- Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [80]:
matrix = np.zeros((file_count, len(unique_words)))
print(matrix) 
unique_word_dict= {}
count = 0
for word in unique_words:
    unique_word_dict[word] = count
    count+=1
print("dictionary of unique words\n",unique_word_dict)
print("dictionary of files\n",files_dict)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
dictionary of unique words
 {'my': 0, 'book': 1, 'is': 2, 'interesting': 3, 'pen': 4, 'this': 5}
dictionary of files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

# Step 5 Fill Term Document Matrix

- Fill the term doc matrix by checking if the unique word exists in a file or not
- If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
- Do the same for all the files present in the directory

In [81]:
#Your code starts here    

for path in os.listdir(directory_path):
    # check if current path is a file
    if os.path.isfile(os.path.join(directory_path, path)) and path != 'synonyms.txt':
        with open(os.path.join(directory_path, path), 'r') as file:
            # read the file and split the words
            words = file.read().split()
            for word in words:
                matrix[files_dict[path], unique_word_dict[word.lower()]] = 1
print(unique_word_dict)
print(matrix)

#Your code ends here

{'my': 0, 'book': 1, 'is': 2, 'interesting': 3, 'pen': 4, 'this': 5}
[[1. 1. 1. 0. 0. 1.]
 [1. 0. 1. 0. 1. 1.]
 [1. 1. 1. 1. 0. 0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [82]:
#Your code starts here    
colVector = np.zeros((len(unique_word_dict),1))
colVector
#Your code ends here

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [85]:
query = input("\nWrite something for searching  ")
# Check every word of query if it exists in the set of unique words or not
# If exists then increment the count of that word in word dictionary
for word in query.split():
    lower_word = word.lower()
    if lower_word in unique_word_dict:
        colVector[unique_word_dict[lower_word]] = 1

print(colVector)
print(unique_word_dict)


Write something for searching   book


[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]
{'my': 0, 'book': 1, 'is': 2, 'interesting': 3, 'pen': 4, 'this': 5}


In [ ]:
#Your code starts here    

#Your code ends here

### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [86]:
#Your code starts here  
result = np.dot(matrix, colVector)
print(result)
index = np.argmax(result)
print('max_index:', index)
print('max_value:', result[index])
#Your code ends here

[[1.]
 [0.]
 [1.]]
max_index: 0
max_value: [1.]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [87]:
#Your code starts here    
def find_file_name(dictionary, target_index):
    for file_name, index in dictionary.items():
        if index == target_index:
            return file_name
    return None  # Return None if the index is not found in the dictionary

file_name = find_file_name(files_dict, index)
with open(os.path.join(directory_path, file_name), 'r') as file:
    print(file.read())
#Your code ends here

This is my book


Congratulations Now you are able to build your own small IRS.